#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnpt.in -o mdnpt.out -p ../00-PREP/system.top -c eqmdnvt-4.restart -ref eqmdnvt-4.restart -r eqmdnpt.restart -x eqmdnpt.nc
