#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnvt-3.in -o mdnvt-3.out -p ../00-PREP/system.top -c eqmdnvt-2.restart -ref eqmdnvt-2.restart -r eqmdnvt-3.restart -x eqmdnvt-3.nc
