#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnvt-4.in -o mdnvt-4.out -p ../00-PREP/system.top -c eqmdnvt-3.restart -ref eqmdnvt-3.restart -r eqmdnvt-4.restart -x eqmdnvt-4.nc
