#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnvt.in -o mdnvt.out -p ../00-PREP/system.top -c ../00-PREP/system.restart -ref ../00-PREP/system.restart -r eqmdnvt.restart -x eqmdnvt.nc
