#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnvt-2.in -o mdnvt-2.out -p ../00-PREP/system.top -c eqmdnvt.restart -ref eqmdnvt.restart -r eqmdnvt-2.restart -x eqmdnvt-2.nc
