#!/bin/bash

module load gcc/6.1.0
module load cuda/9.2
module load amber/18-cuda

pmemd.cuda -O -i  mdnpt-2.in -o mdnpt-2.out -p ../00-PREP/system.top -c eqmdnpt.restart -ref eqmdnpt.restart -r eqmdnpt-2.restart -x eqmdnpt-2.nc
